name: Retire

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  retire:
    permissions:
      checks: write
      contents: read
    name: Retire
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    env:
      TEST_ENV: ${{ matrix.test_env || 'production' }}

    services:
      # help!!! - which dbs??

    steps:
      - uses: actions/checkout@v3

      - run: cp install/package.json package.json

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: NPM Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false  

      # add setup for diff databases

        - name: Run Retirejs
          run: npm run retire